"""Change column types

Revision ID: 04ebb38f107a
Revises: 6318251af2c9
Create Date: 2025-01-28 15:50:25.995443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04ebb38f107a'
down_revision: Union[str, None] = '6318251af2c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'copy_trades', 'user_id',
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True
    )
    op.alter_column(
        'copy_trades', 'name',
        existing_type=sa.VARCHAR(),
        nullable=True
    )
    op.alter_column(
        'limit_orders', 'user_id',
        existing_type=sa.INTEGER(),
        nullable=True
    )
    op.alter_column(
        'limit_orders', 'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=True
    )
    op.drop_index('ix_limit_orders_created_at', table_name='limit_orders')
    op.drop_index('ix_limit_orders_token_address', table_name='limit_orders')
    op.alter_column(
        'users', 'telegram_id',
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users', 'telegram_id',
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True
    )
    op.create_index(
        'ix_limit_orders_token_address',
        'limit_orders',
        ['token_address'],
        unique=False
    )
    op.create_index(
        'ix_limit_orders_created_at',
        'limit_orders',
        ['created_at'],
        unique=False
    )
    op.alter_column(
        'limit_orders', 'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text('now()'),
        existing_nullable=True
    )
    op.alter_column(
        'limit_orders', 'user_id',
        existing_type=sa.INTEGER(),
        nullable=False
    )
    op.alter_column(
        'copy_trades', 'name',
        existing_type=sa.VARCHAR(),
        nullable=False
    )
    op.alter_column(
        'copy_trades', 'user_id',
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True
    )
    # ### end Alembic commands ###
