"""referral_records_trade_id_nullable

Revision ID: 4afad4367709
Revises: e2b7ce040b82
Create Date: 2025-02-02 06:32:35.104055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4afad4367709'
down_revision: Union[str, None] = 'e2b7ce040b82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
