"""change trades created_at

Revision ID: 80124a70cd07
Revises: 8d1eaa4eed0f
Create Date: 2025-01-30 05:36:42.730953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80124a70cd07'
down_revision: Union[str, None] = '8d1eaa4eed0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_trades_timestamp', table_name='trades')
    op.create_index(op.f('ix_trades_created_at'), 'trades', ['created_at'], unique=False)
    op.drop_column('trades', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_trades_created_at'), table_name='trades')
    op.create_index('ix_trades_timestamp', 'trades', ['timestamp'], unique=False)
    op.drop_column('trades', 'created_at')
    # ### end Alembic commands ###
