"""change trades add transaction type remove is_buy

Revision ID: 8d1eaa4eed0f
Revises: 0367ffc70a57
Create Date: 2025-01-30 05:00:56.806753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d1eaa4eed0f'
down_revision: Union[str, None] = '0367ffc70a57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('transaction_type', sa.SmallInteger(), nullable=True))
    op.drop_column('trades', 'is_buy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('is_buy', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('trades', 'transaction_type')
    # ### end Alembic commands ###
