"""add_last_buy_price_for_users

Revision ID: aac53c29e4f0
Revises: aa9a11017d2b
Create Date: 2025-01-21 07:10:59.142277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aac53c29e4f0'
down_revision: Union[str, None] = 'aa9a11017d2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_buy_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_buy_amount')
    # ### end Alembic commands ###
