"""create referral_records_table

Revision ID: e2b7ce040b82
Revises: 80124a70cd07
Create Date: 2025-02-02 06:27:00.505825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2b7ce040b82'
down_revision: Union[str, None] = '80124a70cd07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referral_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('amount_sol', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_records_created_at'), 'referral_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_referral_records_trade_id'), 'referral_records', ['trade_id'], unique=False)
    op.create_index(op.f('ix_referral_records_user_id'), 'referral_records', ['user_id'], unique=False)
    op.alter_column('trades', 'transaction_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=88),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trades', 'transaction_hash',
               existing_type=sa.String(length=88),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_index(op.f('ix_referral_records_user_id'), table_name='referral_records')
    op.drop_index(op.f('ix_referral_records_trade_id'), table_name='referral_records')
    op.drop_index(op.f('ix_referral_records_created_at'), table_name='referral_records')
    op.drop_table('referral_records')
    # ### end Alembic commands ###
